# Generated by Django 4.2.16 on 2026-02-12 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('UPLOAD', 'Carga de documento'), ('OCR_EXTRACT', 'Extracción/OCR'), ('REVIEW_SAVE', 'Guardar revisión'), ('VALIDATE', 'Validar documento'), ('PUBLISH', 'Publicar documento'), ('ENABLE', 'Habilitar documento'), ('DISABLE', 'Inhabilitar documento'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión')], db_index=True, max_length=32)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
