# Generated by Django 4.2.16 on 2026-03-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
