# Generated by Django 4.2.16 on 2026-03-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('UPLOAD', 'Carga de documento'), ('OCR_EXTRACT', 'Extracción/OCR'), ('REVIEW_SAVE', 'Guardar revisión'), ('VALIDATE', 'Validar documento'), ('PUBLISH', 'Publicar documento'), ('ENABLE', 'Habilitar documento'), ('DISABLE', 'Inhabilitar documento'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('DOWNLOAD', 'Descarga de documento')], db_index=True, max_length=32),
        ),
    ]
